settings:
  gametime: 60
  pretime: 5
  deathmatch: 30
  bungeecord: false
  rewriteconfig: false
  chat:
    format: '<&a[&b%points&a]&r%name> %msg'
lobby:
  world: world
  x: 0.5
  y: 1.0
  z: 0.5
  pitch: 0
  yaw: 0
chests:
  contents: 
  - APPLE,3
  - IRON_SWORD,1
  - STONE_AXE,1
  - COOKED_BEEF,3
  - DIAMOND,1
points:
  win: 100
  lose: 20
  kill: 10