name: SurvivalGames
main: com.zanmc.survivalgames.SG
version: 0.1-DEV
author: Superzelda
website: http://zanmc.com
commands:
  sg:
  addspawn:
    permission: sg.admin
  addmap:
    permission: sg.admin
  vote:
  editarena:
    permission: sg.admin
  savearena:
    permission: sg.admin
  fstart:
    permission: sg.admin
  join:
  leave:
  setlobby:
    permission: sg.admin
  tploc:
    permission: sg.admin